// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ADgroup
    {
        /// <summary>
        /// Initializes a new instance of the ADgroup class.
        /// </summary>
        public ADgroup()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ADgroup class.
        /// </summary>
        public ADgroup(string _id = default(string), string objectSid = default(string), string cnname = default(string), string dn = default(string), string name = default(string), string uSNChanged = default(string), string mail = default(string), string roleId = default(string), System.DateTime? created = default(System.DateTime?), System.DateTime? lastUpdated = default(System.DateTime?))
        {
            this._id = _id;
            ObjectSid = objectSid;
            Cnname = cnname;
            Dn = dn;
            Name = name;
            USNChanged = uSNChanged;
            Mail = mail;
            RoleId = roleId;
            Created = created;
            LastUpdated = lastUpdated;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "objectSid")]
        public string ObjectSid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cn/name")]
        public string Cnname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dn")]
        public string Dn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uSNChanged")]
        public string USNChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mail")]
        public string Mail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public string RoleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdated")]
        public System.DateTime? LastUpdated { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ObjectSid != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(ObjectSid, "^\\[\\d{1,3}(?:,\\d{1,3}){27}\\]$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "ObjectSid", "^\\[\\d{1,3}(?:,\\d{1,3}){27}\\]$");
                }
            }
            if (RoleId != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(RoleId, "^[0-9a-fA-F]{24}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "RoleId", "^[0-9a-fA-F]{24}$");
                }
            }
        }
    }
}
