// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AvailableDatasourcesInfoRequest
    /// </summary>
    public partial class AvailableDatasourcesInfoRequest
    {
        /// <summary>
        /// Initializes a new instance of the AvailableDatasourcesInfoRequest
        /// class.
        /// </summary>
        public AvailableDatasourcesInfoRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AvailableDatasourcesInfoRequest
        /// class.
        /// </summary>
        public AvailableDatasourcesInfoRequest(string physicalName = default(string))
        {
            PhysicalName = physicalName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "physicalName")]
        public string PhysicalName { get; set; }

    }
}
