// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// CubeDTO
    /// </summary>
    public partial class CubeDTO
    {
        /// <summary>
        /// Initializes a new instance of the CubeDTO class.
        /// </summary>
        public CubeDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CubeDTO class.
        /// </summary>
        public CubeDTO(string _id = default(string), string buildType = default(string), string createdUtc = default(string), string dataGroupName = default(string), string databaseName = default(string), string elasticubeSet = default(string), string error = default(string), string lastBuiltUtc = default(string), int? permissionsSummary = default(int?), IList<ACLDTO> shares = default(IList<ACLDTO>), double? sizeInMb = default(double?), int? status = default(int?), string title = default(string))
        {
            this._id = _id;
            BuildType = buildType;
            CreatedUtc = createdUtc;
            DataGroupName = dataGroupName;
            DatabaseName = databaseName;
            ElasticubeSet = elasticubeSet;
            Error = error;
            LastBuiltUtc = lastBuiltUtc;
            PermissionsSummary = permissionsSummary;
            Shares = shares;
            SizeInMb = sizeInMb;
            Status = status;
            Title = title;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildType")]
        public string BuildType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdUtc")]
        public string CreatedUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataGroupName")]
        public string DataGroupName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "databaseName")]
        public string DatabaseName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elasticubeSet")]
        public string ElasticubeSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastBuiltUtc")]
        public string LastBuiltUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permissionsSummary")]
        public int? PermissionsSummary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shares")]
        public IList<ACLDTO> Shares { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sizeInMb")]
        public double? SizeInMb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public int? Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

    }
}
