// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Logo
    {
        /// <summary>
        /// Initializes a new instance of the Logo class.
        /// </summary>
        public Logo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Logo class.
        /// </summary>
        public Logo(LogoDesktop desktop = default(LogoDesktop), LogoPhone phone = default(LogoPhone), LogoTablet tablet = default(LogoTablet))
        {
            Desktop = desktop;
            Phone = phone;
            Tablet = tablet;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "desktop")]
        public LogoDesktop Desktop { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public LogoPhone Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tablet")]
        public LogoTablet Tablet { get; set; }

    }
}
