// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Recipient
    {
        /// <summary>
        /// Initializes a new instance of the Recipient class.
        /// </summary>
        public Recipient()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Recipient class.
        /// </summary>
        public Recipient(string recipientProperty = default(string), string type = default(string))
        {
            RecipientProperty = recipientProperty;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipient")]
        public string RecipientProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
