// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReportTypePdf
    {
        /// <summary>
        /// Initializes a new instance of the ReportTypePdf class.
        /// </summary>
        public ReportTypePdf()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReportTypePdf class.
        /// </summary>
        public ReportTypePdf(bool? includeDS = default(bool?), bool? includeFilters = default(bool?), bool? includeTitle = default(bool?), ReportTypePdfRenderingInfo renderingInfo = default(ReportTypePdfRenderingInfo))
        {
            IncludeDS = includeDS;
            IncludeFilters = includeFilters;
            IncludeTitle = includeTitle;
            RenderingInfo = renderingInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeDS")]
        public bool? IncludeDS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeFilters")]
        public bool? IncludeFilters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeTitle")]
        public bool? IncludeTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "renderingInfo")]
        public ReportTypePdfRenderingInfo RenderingInfo { get; set; }

    }
}
