// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SendReports
    {
        /// <summary>
        /// Initializes a new instance of the SendReports class.
        /// </summary>
        public SendReports()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SendReports class.
        /// </summary>
        public SendReports(string assetId = default(string), string assetType = default(string), IList<Recipient> recipients = default(IList<Recipient>))
        {
            AssetId = assetId;
            AssetType = assetType;
            Recipients = recipients;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetType")]
        public string AssetType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipients")]
        public IList<Recipient> Recipients { get; set; }

    }
}
