// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Server
    {
        /// <summary>
        /// Initializes a new instance of the Server class.
        /// </summary>
        public Server()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Server class.
        /// </summary>
        /// <param name="defaultCubePermissions">defaultCubePermissions can be
        /// either an array of ACL objects OR an object of the type {
        /// 'everyone' : bool }, where 'everyone' indicates whether to grant
        /// permissions to the 'everyone' group, or to no-one</param>
        public Server(string _id = default(string), string address = default(string), System.DateTime? created = default(System.DateTime?), IList<Acl> defaultCubePermissions = default(IList<Acl>), System.DateTime? lastUpdated = default(System.DateTime?), string owner = default(string))
        {
            this._id = _id;
            Address = address;
            Created = created;
            DefaultCubePermissions = defaultCubePermissions;
            LastUpdated = lastUpdated;
            Owner = owner;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// Gets or sets defaultCubePermissions can be either an array of ACL
        /// objects OR an object of the type { 'everyone' : bool }, where
        /// 'everyone' indicates whether to grant permissions to the 'everyone'
        /// group, or to no-one
        /// </summary>
        [JsonProperty(PropertyName = "defaultCubePermissions")]
        public IList<Acl> DefaultCubePermissions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdated")]
        public System.DateTime? LastUpdated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string Owner { get; set; }

    }
}
