// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SharesSubscription
    {
        /// <summary>
        /// Initializes a new instance of the SharesSubscription class.
        /// </summary>
        public SharesSubscription()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SharesSubscription class.
        /// </summary>
        public SharesSubscription(object context = default(object), EmailSettings emailSettings = default(EmailSettings), double? executionPerDay = default(double?), bool? isDataChange = default(bool?), ReportType reportType = default(ReportType), string schedule = default(string), System.DateTime? startAt = default(System.DateTime?), bool? subscribe = default(bool?), string timezone = default(string), string type = default(string), string tzName = default(string))
        {
            Context = context;
            EmailSettings = emailSettings;
            ExecutionPerDay = executionPerDay;
            IsDataChange = isDataChange;
            ReportType = reportType;
            Schedule = schedule;
            StartAt = startAt;
            Subscribe = subscribe;
            Timezone = timezone;
            Type = type;
            TzName = tzName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public object Context { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailSettings")]
        public EmailSettings EmailSettings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executionPerDay")]
        public double? ExecutionPerDay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDataChange")]
        public bool? IsDataChange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reportType")]
        public ReportType ReportType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schedule")]
        public string Schedule { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "startAt")]
        public System.DateTime? StartAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscribe")]
        public bool? Subscribe { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tzName")]
        public string TzName { get; set; }

    }
}
