// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SharesToObject
    {
        /// <summary>
        /// Initializes a new instance of the SharesToObject class.
        /// </summary>
        public SharesToObject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SharesToObject class.
        /// </summary>
        public SharesToObject(bool? isGroup = default(bool?), object rule = default(object), string shareId = default(string), bool? subscribe = default(bool?))
        {
            IsGroup = isGroup;
            Rule = rule;
            ShareId = shareId;
            Subscribe = subscribe;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isGroup")]
        public bool? IsGroup { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rule")]
        public object Rule { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shareId")]
        public string ShareId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscribe")]
        public bool? Subscribe { get; set; }

    }
}
