// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddAlertContext
    {
        /// <summary>
        /// Initializes a new instance of the AddAlertContext class.
        /// </summary>
        public AddAlertContext()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddAlertContext class.
        /// </summary>
        public AddAlertContext(bool? backToNormal = default(bool?), bool? buildSuccessAfterFailed = default(bool?), bool? buildSuccess = default(bool?), bool? buildFailed = default(bool?), AddAlertContextKpi kpi = default(AddAlertContextKpi), string dashboard = default(string), bool? notifyOnceMet = default(bool?), bool? notifyNotMet = default(bool?), AddAlertContextCondition condition = default(AddAlertContextCondition), string locale = default(string), IList<AddAlertContextSourcesItem> sources = default(IList<AddAlertContextSourcesItem>))
        {
            BackToNormal = backToNormal;
            BuildSuccessAfterFailed = buildSuccessAfterFailed;
            BuildSuccess = buildSuccess;
            BuildFailed = buildFailed;
            Kpi = kpi;
            Dashboard = dashboard;
            NotifyOnceMet = notifyOnceMet;
            NotifyNotMet = notifyNotMet;
            Condition = condition;
            Locale = locale;
            Sources = sources;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "backToNormal")]
        public bool? BackToNormal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildSuccessAfterFailed")]
        public bool? BuildSuccessAfterFailed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildSuccess")]
        public bool? BuildSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildFailed")]
        public bool? BuildFailed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kpi")]
        public AddAlertContextKpi Kpi { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dashboard")]
        public string Dashboard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notifyOnceMet")]
        public bool? NotifyOnceMet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notifyNotMet")]
        public bool? NotifyNotMet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "condition")]
        public AddAlertContextCondition Condition { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sources")]
        public IList<AddAlertContextSourcesItem> Sources { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Kpi != null)
            {
                Kpi.Validate();
            }
            if (Dashboard != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Dashboard, "^[0-9a-fA-F]{24}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Dashboard", "^[0-9a-fA-F]{24}$");
                }
            }
            if (Condition != null)
            {
                Condition.Validate();
            }
            if (Sources != null)
            {
                if (Sources.Count != System.Linq.Enumerable.Count(System.Linq.Enumerable.Distinct(Sources)))
                {
                    throw new ValidationException(ValidationRules.UniqueItems, "Sources");
                }
                foreach (var element in Sources)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
