// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddAlertAction
    {
        /// <summary>
        /// Initializes a new instance of the AddAlertAction class.
        /// </summary>
        public AddAlertAction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddAlertAction class.
        /// </summary>
        public AddAlertAction(bool? email = default(bool?), bool? mobile = default(bool?), bool? feed = default(bool?), AddAlertActionSlack slack = default(AddAlertActionSlack), AddAlertActionZapier zapier = default(AddAlertActionZapier), IList<AddAlertActionWebhooksItem> webhooks = default(IList<AddAlertActionWebhooksItem>))
        {
            Email = email;
            Mobile = mobile;
            Feed = feed;
            Slack = slack;
            Zapier = zapier;
            Webhooks = webhooks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public bool? Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mobile")]
        public bool? Mobile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "feed")]
        public bool? Feed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "slack")]
        public AddAlertActionSlack Slack { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zapier")]
        public AddAlertActionZapier Zapier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "webhooks")]
        public IList<AddAlertActionWebhooksItem> Webhooks { get; set; }

    }
}
