// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItem
        /// class.
        /// </summary>
        public AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItem
        /// class.
        /// </summary>
        public AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItem(double? width = default(double?), IList<AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItemCellsItem> cells = default(IList<AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItemCellsItem>))
        {
            Width = width;
            Cells = cells;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public double? Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cells")]
        public IList<AddDashboardCreatedResponsePreviewLayoutItemPagesItemColumnsItemCellsItem> Cells { get; set; }

    }
}
