// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AddServerAccessBadRequestResponse
    {
        /// <summary>
        /// Initializes a new instance of the AddServerAccessBadRequestResponse
        /// class.
        /// </summary>
        public AddServerAccessBadRequestResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddServerAccessBadRequestResponse
        /// class.
        /// </summary>
        public AddServerAccessBadRequestResponse(AddServerAccessBadRequestResponseError error = default(AddServerAccessBadRequestResponseError))
        {
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public AddServerAccessBadRequestResponseError Error { get; set; }

    }
}
