// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApplicationStatus
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationStatus class.
        /// </summary>
        public ApplicationStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationStatus class.
        /// </summary>
        public ApplicationStatus(ApplicationStatusVersion version, ApplicationStatusLicense license)
        {
            Version = version;
            License = license;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public ApplicationStatusVersion Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "license")]
        public ApplicationStatusLicense License { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Version == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Version");
            }
            if (License == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "License");
            }
        }
    }
}
