// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApplicationStatusLicense
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationStatusLicense class.
        /// </summary>
        public ApplicationStatusLicense()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationStatusLicense class.
        /// </summary>
        public ApplicationStatusLicense(bool? isMobileEnabled = default(bool?), bool? isExpired = default(bool?))
        {
            IsMobileEnabled = isMobileEnabled;
            IsExpired = isExpired;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isMobileEnabled")]
        public bool? IsMobileEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isExpired")]
        public bool? IsExpired { get; set; }

    }
}
