// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItem
        /// class.
        /// </summary>
        public BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItem
        /// class.
        /// </summary>
        public BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItem(IList<BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItemElementsItem> elements = default(IList<BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItemElementsItem>))
        {
            Elements = elements;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elements")]
        public IList<BaseDashboardPreviewLayoutItemPagesItemColumnsItemCellsItemSubcellsItemElementsItem> Elements { get; set; }

    }
}
