// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ConnectionStatus
    /// </summary>
    public partial class ConnectionStatus
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionStatus class.
        /// </summary>
        public ConnectionStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectionStatus class.
        /// </summary>
        public ConnectionStatus(string status = default(string))
        {
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
