// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConnectionWithDuplicates
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionWithDuplicates class.
        /// </summary>
        public ConnectionWithDuplicates()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectionWithDuplicates class.
        /// </summary>
        public ConnectionWithDuplicates(string _id = default(string), string owner = default(string), string provider = default(string), double? timeout = default(double?), double? refreshRate = default(double?), string timezone = default(string), string schema = default(string), object parameters = default(object), IList<ConnectionWithDuplicatesDuplicatesItem> duplicates = default(IList<ConnectionWithDuplicatesDuplicatesItem>))
        {
            this._id = _id;
            Owner = owner;
            Provider = provider;
            Timeout = timeout;
            RefreshRate = refreshRate;
            Timezone = timezone;
            Schema = schema;
            Parameters = parameters;
            Duplicates = duplicates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provider")]
        public string Provider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeout")]
        public double? Timeout { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refreshRate")]
        public double? RefreshRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schema")]
        public string Schema { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameters")]
        public object Parameters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duplicates")]
        public IList<ConnectionWithDuplicatesDuplicatesItem> Duplicates { get; set; }

    }
}
