// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConnectionWithDuplicatesDuplicatesItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ConnectionWithDuplicatesDuplicatesItem class.
        /// </summary>
        public ConnectionWithDuplicatesDuplicatesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ConnectionWithDuplicatesDuplicatesItem class.
        /// </summary>
        public ConnectionWithDuplicatesDuplicatesItem(string _id = default(string), double? timeout = default(double?), double? refreshRate = default(double?), string timezone = default(string))
        {
            this._id = _id;
            Timeout = timeout;
            RefreshRate = refreshRate;
            Timezone = timezone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeout")]
        public double? Timeout { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "refreshRate")]
        public double? RefreshRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

    }
}
