// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ConnectorManifest
    /// </summary>
    public partial class ConnectorManifest
    {
        /// <summary>
        /// Initializes a new instance of the ConnectorManifest class.
        /// </summary>
        public ConnectorManifest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectorManifest class.
        /// </summary>
        public ConnectorManifest(string name = default(string), TitleCustomization titleCustomization = default(TitleCustomization), Connection connection = default(Connection))
        {
            Name = name;
            TitleCustomization = titleCustomization;
            Connection = connection;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "titleCustomization")]
        public TitleCustomization TitleCustomization { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connection")]
        public Connection Connection { get; set; }

    }
}
