// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConnectorManifestTitleCustomization
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ConnectorManifestTitleCustomization class.
        /// </summary>
        public ConnectorManifestTitleCustomization()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ConnectorManifestTitleCustomization class.
        /// </summary>
        public ConnectorManifestTitleCustomization(ConnectorManifestTitleCustomizationDatabase database = default(ConnectorManifestTitleCustomizationDatabase), ConnectorManifestTitleCustomizationTable table = default(ConnectorManifestTitleCustomizationTable))
        {
            Database = database;
            Table = table;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "database")]
        public ConnectorManifestTitleCustomizationDatabase Database { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public ConnectorManifestTitleCustomizationTable Table { get; set; }

    }
}
