// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConnectorManifestConnection
    {
        /// <summary>
        /// Initializes a new instance of the ConnectorManifestConnection
        /// class.
        /// </summary>
        public ConnectorManifestConnection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectorManifestConnection
        /// class.
        /// </summary>
        public ConnectorManifestConnection(ConnectorManifestConnectionOauth2 oauth2 = default(ConnectorManifestConnectionOauth2), IList<ConnectorManifestConnectionBaseItem> baseProperty = default(IList<ConnectorManifestConnectionBaseItem>))
        {
            Oauth2 = oauth2;
            BaseProperty = baseProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "oauth2")]
        public ConnectorManifestConnectionOauth2 Oauth2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "base")]
        public IList<ConnectorManifestConnectionBaseItem> BaseProperty { get; set; }

    }
}
