// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DatasourceDimension
    {
        /// <summary>
        /// Initializes a new instance of the DatasourceDimension class.
        /// </summary>
        public DatasourceDimension()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasourceDimension class.
        /// </summary>
        public DatasourceDimension(string id = default(string), string column = default(string), string table = default(string), string dimtype = default(string), bool? indexed = default(bool?), bool? merged = default(bool?), string title = default(string), string type = default(string))
        {
            Id = id;
            Column = column;
            Table = table;
            Dimtype = dimtype;
            Indexed = indexed;
            Merged = merged;
            Title = title;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "column")]
        public string Column { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dimtype")]
        public string Dimtype { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexed")]
        public bool? Indexed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merged")]
        public bool? Merged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
