// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DatasetToAdd
    {
        /// <summary>
        /// Initializes a new instance of the DatasetToAdd class.
        /// </summary>
        public DatasetToAdd()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetToAdd class.
        /// </summary>
        /// <param name="elasticube">oid of elasticube</param>
        /// <param name="type">Possible values include: 'live',
        /// 'extract'</param>
        public DatasetToAdd(System.Guid elasticube, string name, string type, string connection, IList<DatasetToAddModelingTransformationsItem> modelingTransformations = default(IList<DatasetToAddModelingTransformationsItem>), DatasetToAddSchema schema = default(DatasetToAddSchema), DatasetToAddSchedule schedule = default(DatasetToAddSchedule))
        {
            Elasticube = elasticube;
            Name = name;
            Type = type;
            Connection = connection;
            ModelingTransformations = modelingTransformations;
            Schema = schema;
            Schedule = schedule;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets oid of elasticube
        /// </summary>
        [JsonProperty(PropertyName = "elasticube")]
        public System.Guid Elasticube { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'live', 'extract'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connection")]
        public string Connection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modeling-transformations")]
        public IList<DatasetToAddModelingTransformationsItem> ModelingTransformations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schema")]
        public DatasetToAddSchema Schema { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schedule")]
        public DatasetToAddSchedule Schedule { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (Connection == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Connection");
            }
            if (Connection != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Connection, "^[0-9a-fA-F]{24}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Connection", "^[0-9a-fA-F]{24}$");
                }
            }
        }
    }
}
