// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DatasetUpdatedPropertiesSchemaTablesItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DatasetUpdatedPropertiesSchemaTablesItem class.
        /// </summary>
        public DatasetUpdatedPropertiesSchemaTablesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DatasetUpdatedPropertiesSchemaTablesItem class.
        /// </summary>
        public DatasetUpdatedPropertiesSchemaTablesItem(string id = default(string), string name = default(string), IList<DatasetUpdatedPropertiesSchemaTablesItemColumnsItem> columns = default(IList<DatasetUpdatedPropertiesSchemaTablesItemColumnsItem>), IList<DatasetUpdatedPropertiesSchemaTablesItemTupleTransformationsItem> tupleTransformations = default(IList<DatasetUpdatedPropertiesSchemaTablesItemTupleTransformationsItem>))
        {
            Id = id;
            Name = name;
            Columns = columns;
            TupleTransformations = tupleTransformations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columns")]
        public IList<DatasetUpdatedPropertiesSchemaTablesItemColumnsItem> Columns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tuple-transformations")]
        public IList<DatasetUpdatedPropertiesSchemaTablesItemTupleTransformationsItem> TupleTransformations { get; set; }

    }
}
