// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DatasetTableColumnsItem
    {
        /// <summary>
        /// Initializes a new instance of the DatasetTableColumnsItem class.
        /// </summary>
        public DatasetTableColumnsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetTableColumnsItem class.
        /// </summary>
        public DatasetTableColumnsItem(string id = default(string), string name = default(string), double? type = default(double?), double? size = default(double?), double? scale = default(double?), double? precision = default(double?), System.Guid? oid = default(System.Guid?), string lastUpdated = default(string))
        {
            Id = id;
            Name = name;
            Type = type;
            Size = size;
            Scale = scale;
            Precision = precision;
            Oid = oid;
            LastUpdated = lastUpdated;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public double? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public double? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scale")]
        public double? Scale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "precision")]
        public double? Precision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "oid")]
        public System.Guid? Oid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdated")]
        public string LastUpdated { get; set; }

    }
}
