// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DatasetToAddSchema
    {
        /// <summary>
        /// Initializes a new instance of the DatasetToAddSchema class.
        /// </summary>
        public DatasetToAddSchema()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatasetToAddSchema class.
        /// </summary>
        public DatasetToAddSchema(IList<DatasetToAddSchemaTablesItem> tables = default(IList<DatasetToAddSchemaTablesItem>))
        {
            Tables = tables;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tables")]
        public IList<DatasetToAddSchemaTablesItem> Tables { get; set; }

    }
}
