// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DesignSettingsDashboards
    {
        /// <summary>
        /// Initializes a new instance of the DesignSettingsDashboards class.
        /// </summary>
        public DesignSettingsDashboards()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DesignSettingsDashboards class.
        /// </summary>
        /// <param name="toolbarTextColor">Affects the dashboard title text and
        /// the icons color</param>
        /// <param name="toolbarSecondaryTextColor">Used for elements in the
        /// toolbar that are not highlighted such as the date, data source
        /// name</param>
        /// <param name="colorPaletteName">Affects newly created
        /// dashboards</param>
        /// <param name="navBackgroundColor">Navigation panel background
        /// color</param>
        /// <param name="navTextColor">Navigation panel text color. Used for
        /// titles, menus, icons color and more</param>
        /// <param name="navTextHoverColor">Navigation panel text hover color.
        /// Mouse-over text color</param>
        /// <param name="navHoverBackgroundColor">Mouse-over
        /// background-color</param>
        /// <param name="panelBackgroundColor">The background color around
        /// filters</param>
        /// <param name="panelTitleTextColor">The text and icons color inside
        /// the background around the filters</param>
        /// <param name="widgetTextColor">Affects the text color inside the
        /// widget itself, such as data labels and legends</param>
        /// <param name="widgetTitleColor">Affects the widget title primary
        /// text and the icons color</param>
        public DesignSettingsDashboards(string toolbarBackgroundColor = default(string), string toolbarTextColor = default(string), string toolbarSecondaryTextColor = default(string), string colorPaletteName = default(string), string navBackgroundColor = default(string), string navTextColor = default(string), string navTextHoverColor = default(string), string navHoverBackgroundColor = default(string), string panelBackgroundColor = default(string), string panelTitleTextColor = default(string), string widgetTextColor = default(string), string widgetSecondaryTextColor = default(string), string widgetBackgroundColor = default(string), string widgetTitleBackgroundColor = default(string), string widgetTitleColor = default(string), string widgetSecondaryTitleColor = default(string))
        {
            ToolbarBackgroundColor = toolbarBackgroundColor;
            ToolbarTextColor = toolbarTextColor;
            ToolbarSecondaryTextColor = toolbarSecondaryTextColor;
            ColorPaletteName = colorPaletteName;
            NavBackgroundColor = navBackgroundColor;
            NavTextColor = navTextColor;
            NavTextHoverColor = navTextHoverColor;
            NavHoverBackgroundColor = navHoverBackgroundColor;
            PanelBackgroundColor = panelBackgroundColor;
            PanelTitleTextColor = panelTitleTextColor;
            WidgetTextColor = widgetTextColor;
            WidgetSecondaryTextColor = widgetSecondaryTextColor;
            WidgetBackgroundColor = widgetBackgroundColor;
            WidgetTitleBackgroundColor = widgetTitleBackgroundColor;
            WidgetTitleColor = widgetTitleColor;
            WidgetSecondaryTitleColor = widgetSecondaryTitleColor;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toolbarBackgroundColor")]
        public string ToolbarBackgroundColor { get; set; }

        /// <summary>
        /// Gets or sets affects the dashboard title text and the icons color
        /// </summary>
        [JsonProperty(PropertyName = "toolbarTextColor")]
        public string ToolbarTextColor { get; set; }

        /// <summary>
        /// Gets or sets used for elements in the toolbar that are not
        /// highlighted such as the date, data source name
        /// </summary>
        [JsonProperty(PropertyName = "toolbarSecondaryTextColor")]
        public string ToolbarSecondaryTextColor { get; set; }

        /// <summary>
        /// Gets or sets affects newly created dashboards
        /// </summary>
        [JsonProperty(PropertyName = "colorPaletteName")]
        public string ColorPaletteName { get; set; }

        /// <summary>
        /// Gets or sets navigation panel background color
        /// </summary>
        [JsonProperty(PropertyName = "navBackgroundColor")]
        public string NavBackgroundColor { get; set; }

        /// <summary>
        /// Gets or sets navigation panel text color. Used for titles, menus,
        /// icons color and more
        /// </summary>
        [JsonProperty(PropertyName = "navTextColor")]
        public string NavTextColor { get; set; }

        /// <summary>
        /// Gets or sets navigation panel text hover color. Mouse-over text
        /// color
        /// </summary>
        [JsonProperty(PropertyName = "navTextHoverColor")]
        public string NavTextHoverColor { get; set; }

        /// <summary>
        /// Gets or sets mouse-over background-color
        /// </summary>
        [JsonProperty(PropertyName = "navHoverBackgroundColor")]
        public string NavHoverBackgroundColor { get; set; }

        /// <summary>
        /// Gets or sets the background color around filters
        /// </summary>
        [JsonProperty(PropertyName = "panelBackgroundColor")]
        public string PanelBackgroundColor { get; set; }

        /// <summary>
        /// Gets or sets the text and icons color inside the background around
        /// the filters
        /// </summary>
        [JsonProperty(PropertyName = "panelTitleTextColor")]
        public string PanelTitleTextColor { get; set; }

        /// <summary>
        /// Gets or sets affects the text color inside the widget itself, such
        /// as data labels and legends
        /// </summary>
        [JsonProperty(PropertyName = "widgetTextColor")]
        public string WidgetTextColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetSecondaryTextColor")]
        public string WidgetSecondaryTextColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetBackgroundColor")]
        public string WidgetBackgroundColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetTitleBackgroundColor")]
        public string WidgetTitleBackgroundColor { get; set; }

        /// <summary>
        /// Gets or sets affects the widget title primary text and the icons
        /// color
        /// </summary>
        [JsonProperty(PropertyName = "widgetTitleColor")]
        public string WidgetTitleColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetSecondaryTitleColor")]
        public string WidgetSecondaryTitleColor { get; set; }

    }
}
