// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DesignSettingsGeneral
    {
        /// <summary>
        /// Initializes a new instance of the DesignSettingsGeneral class.
        /// </summary>
        public DesignSettingsGeneral()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DesignSettingsGeneral class.
        /// </summary>
        /// <param name="brandColor">The main color appears in various elements
        /// across the application including buttons, toggle controls, active
        /// tabs, filter labels and more</param>
        /// <param name="primaryButtonHoverColor">Mouse-over button
        /// color</param>
        /// <param name="primaryButtonTextColor">The color of the text inside
        /// buttons</param>
        /// <param name="secondaryButtonHoverColor">Mouse-over button
        /// color</param>
        /// <param name="secondaryButtonTextColor">The color of the text inside
        /// the button</param>
        public DesignSettingsGeneral(string brandColor = default(string), string primaryButtonHoverColor = default(string), string primaryButtonTextColor = default(string), string secondaryButtonBaseColor = default(string), string secondaryButtonHoverColor = default(string), string secondaryButtonTextColor = default(string), DesignSettingsGeneralMarketingBanner marketingBanner = default(DesignSettingsGeneralMarketingBanner))
        {
            BrandColor = brandColor;
            PrimaryButtonHoverColor = primaryButtonHoverColor;
            PrimaryButtonTextColor = primaryButtonTextColor;
            SecondaryButtonBaseColor = secondaryButtonBaseColor;
            SecondaryButtonHoverColor = secondaryButtonHoverColor;
            SecondaryButtonTextColor = secondaryButtonTextColor;
            MarketingBanner = marketingBanner;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the main color appears in various elements across the
        /// application including buttons, toggle controls, active tabs, filter
        /// labels and more
        /// </summary>
        [JsonProperty(PropertyName = "brandColor")]
        public string BrandColor { get; set; }

        /// <summary>
        /// Gets or sets mouse-over button color
        /// </summary>
        [JsonProperty(PropertyName = "primaryButtonHoverColor")]
        public string PrimaryButtonHoverColor { get; set; }

        /// <summary>
        /// Gets or sets the color of the text inside buttons
        /// </summary>
        [JsonProperty(PropertyName = "primaryButtonTextColor")]
        public string PrimaryButtonTextColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondaryButtonBaseColor")]
        public string SecondaryButtonBaseColor { get; set; }

        /// <summary>
        /// Gets or sets mouse-over button color
        /// </summary>
        [JsonProperty(PropertyName = "secondaryButtonHoverColor")]
        public string SecondaryButtonHoverColor { get; set; }

        /// <summary>
        /// Gets or sets the color of the text inside the button
        /// </summary>
        [JsonProperty(PropertyName = "secondaryButtonTextColor")]
        public string SecondaryButtonTextColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marketingBanner")]
        public DesignSettingsGeneralMarketingBanner MarketingBanner { get; set; }

    }
}
