// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DesignSettingsGeneralMarketingBanner
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DesignSettingsGeneralMarketingBanner class.
        /// </summary>
        public DesignSettingsGeneralMarketingBanner()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DesignSettingsGeneralMarketingBanner class.
        /// </summary>
        public DesignSettingsGeneralMarketingBanner(string url = default(string), bool? showBanner = default(bool?), bool? replaceBanner = default(bool?))
        {
            Url = url;
            ShowBanner = showBanner;
            ReplaceBanner = replaceBanner;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "showBanner")]
        public bool? ShowBanner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "replaceBanner")]
        public bool? ReplaceBanner { get; set; }

    }
}
