// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ElasticubeRelationToAdd
    {
        /// <summary>
        /// Initializes a new instance of the ElasticubeRelationToAdd class.
        /// </summary>
        public ElasticubeRelationToAdd()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ElasticubeRelationToAdd class.
        /// </summary>
        public ElasticubeRelationToAdd(IList<ElasticubeRelationToAddColumnsItem> columns = default(IList<ElasticubeRelationToAddColumnsItem>))
        {
            Columns = columns;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columns")]
        public IList<ElasticubeRelationToAddColumnsItem> Columns { get; set; }

    }
}
