// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FolderToUpdate
    {
        /// <summary>
        /// Initializes a new instance of the FolderToUpdate class.
        /// </summary>
        public FolderToUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FolderToUpdate class.
        /// </summary>
        public FolderToUpdate(string name = default(string), string parentId = default(string), string owner = default(string))
        {
            Name = name;
            ParentId = parentId;
            Owner = owner;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentId")]
        public string ParentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public string Owner { get; set; }

    }
}
