// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Insight
    {
        /// <summary>
        /// Initializes a new instance of the Insight class.
        /// </summary>
        public Insight()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Insight class.
        /// </summary>
        public Insight(string dashboardId = default(string), string widgetId = default(string), string widgetName = default(string), string analysisType = default(string), string description = default(string), string narration = default(string), IList<string> images = default(IList<string>))
        {
            DashboardId = dashboardId;
            WidgetId = widgetId;
            WidgetName = widgetName;
            AnalysisType = analysisType;
            Description = description;
            Narration = narration;
            Images = images;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dashboardId")]
        public string DashboardId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetId")]
        public string WidgetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetName")]
        public string WidgetName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "analysisType")]
        public string AnalysisType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "narration")]
        public string Narration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<string> Images { get; set; }

    }
}
