// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Job context
    /// </summary>
    public partial class JobContext
    {
        /// <summary>
        /// Initializes a new instance of the JobContext class.
        /// </summary>
        public JobContext()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobContext class.
        /// </summary>
        /// <param name="dashboardid">Dashboard id</param>
        public JobContext(string dashboardid = default(string))
        {
            Dashboardid = dashboardid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets dashboard id
        /// </summary>
        [JsonProperty(PropertyName = "dashboardid")]
        public string Dashboardid { get; set; }

    }
}
