// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LayoutColumnsItemCellsItemSubcellsItemElementsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// LayoutColumnsItemCellsItemSubcellsItemElementsItem class.
        /// </summary>
        public LayoutColumnsItemCellsItemSubcellsItemElementsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// LayoutColumnsItemCellsItemSubcellsItemElementsItem class.
        /// </summary>
        public LayoutColumnsItemCellsItemSubcellsItemElementsItem(string widgetId = default(string), double? minHeight = default(double?), double? maxHeight = default(double?), double? minWidth = default(double?), double? maxWidth = default(double?), double? height = default(double?), double? defaultWidth = default(double?))
        {
            WidgetId = widgetId;
            MinHeight = minHeight;
            MaxHeight = maxHeight;
            MinWidth = minWidth;
            MaxWidth = maxWidth;
            Height = height;
            DefaultWidth = defaultWidth;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "widgetId")]
        public string WidgetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minHeight")]
        public double? MinHeight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxHeight")]
        public double? MaxHeight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minWidth")]
        public double? MinWidth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxWidth")]
        public double? MaxWidth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public double? Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defaultWidth")]
        public double? DefaultWidth { get; set; }

    }
}
