// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LdapDomainRequest
    {
        /// <summary>
        /// Initializes a new instance of the LdapDomainRequest class.
        /// </summary>
        public LdapDomainRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LdapDomainRequest class.
        /// </summary>
        public LdapDomainRequest(bool? enabled = default(bool?), string url = default(string), string baseDN = default(string), string username = default(string), string password = default(string), string name = default(string), bool? syncActive = default(bool?), int? syncInterval = default(int?), bool? sslEnabled = default(bool?), string pfxCertificate = default(string), string pfxKey = default(string))
        {
            Enabled = enabled;
            Url = url;
            BaseDN = baseDN;
            Username = username;
            Password = password;
            Name = name;
            SyncActive = syncActive;
            SyncInterval = syncInterval;
            SslEnabled = sslEnabled;
            PfxCertificate = pfxCertificate;
            PfxKey = pfxKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseDN")]
        public string BaseDN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "syncActive")]
        public bool? SyncActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "syncInterval")]
        public int? SyncInterval { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sslEnabled")]
        public bool? SslEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pfxCertificate")]
        public string PfxCertificate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pfxKey")]
        public string PfxKey { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Url != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Url, "^ldap|ldaps\\:\\/\\/.+"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Url", "^ldap|ldaps\\:\\/\\/.+");
                }
            }
        }
    }
}
