// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NarrationWidgetRequestJaqlRequestMetadataItemField
    {
        /// <summary>
        /// Initializes a new instance of the
        /// NarrationWidgetRequestJaqlRequestMetadataItemField class.
        /// </summary>
        public NarrationWidgetRequestJaqlRequestMetadataItemField()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// NarrationWidgetRequestJaqlRequestMetadataItemField class.
        /// </summary>
        public NarrationWidgetRequestJaqlRequestMetadataItemField(string id = default(string), int? index = default(int?))
        {
            Id = id;
            Index = index;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "index")]
        public int? Index { get; set; }

    }
}
