// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// narration configuration
    /// </summary>
    public partial class NarrationWidgetRequestNarration
    {
        /// <summary>
        /// Initializes a new instance of the NarrationWidgetRequestNarration
        /// class.
        /// </summary>
        public NarrationWidgetRequestNarration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NarrationWidgetRequestNarration
        /// class.
        /// </summary>
        /// <param name="format">narration text format. Possible values
        /// include: 'bullets', 'paragraph'</param>
        /// <param name="verbosity">narration text verbosity. Possible values
        /// include: 'medium', 'high', 'low'</param>
        /// <param name="upSentiment">narration text sentiment. Possible values
        /// include: 'good', 'bad'</param>
        /// <param name="aggregation">narration text aggregation. Possible
        /// values include: 'sum', 'average'</param>
        public NarrationWidgetRequestNarration(string format = default(string), string verbosity = default(string), string upSentiment = default(string), string aggregation = default(string))
        {
            Format = format;
            Verbosity = verbosity;
            UpSentiment = upSentiment;
            Aggregation = aggregation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets narration text format. Possible values include:
        /// 'bullets', 'paragraph'
        /// </summary>
        [JsonProperty(PropertyName = "format")]
        public string Format { get; set; }

        /// <summary>
        /// Gets or sets narration text verbosity. Possible values include:
        /// 'medium', 'high', 'low'
        /// </summary>
        [JsonProperty(PropertyName = "verbosity")]
        public string Verbosity { get; set; }

        /// <summary>
        /// Gets or sets narration text sentiment. Possible values include:
        /// 'good', 'bad'
        /// </summary>
        [JsonProperty(PropertyName = "up_sentiment")]
        public string UpSentiment { get; set; }

        /// <summary>
        /// Gets or sets narration text aggregation. Possible values include:
        /// 'sum', 'average'
        /// </summary>
        [JsonProperty(PropertyName = "aggregation")]
        public string Aggregation { get; set; }

    }
}
