// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NarrationWidgetResponse
    {
        /// <summary>
        /// Initializes a new instance of the NarrationWidgetResponse class.
        /// </summary>
        public NarrationWidgetResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NarrationWidgetResponse class.
        /// </summary>
        /// <param name="narration">narration text</param>
        public NarrationWidgetResponse(string narration = default(string))
        {
            Narration = narration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets narration text
        /// </summary>
        [JsonProperty(PropertyName = "narration")]
        public string Narration { get; set; }

    }
}
