// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PermissionsCubeItemUsersItem
    {
        /// <summary>
        /// Initializes a new instance of the PermissionsCubeItemUsersItem
        /// class.
        /// </summary>
        public PermissionsCubeItemUsersItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PermissionsCubeItemUsersItem
        /// class.
        /// </summary>
        public PermissionsCubeItemUsersItem(string id = default(string), string email = default(string))
        {
            Id = id;
            Email = email;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

    }
}
