// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Permission
    {
        /// <summary>
        /// Initializes a new instance of the Permission class.
        /// </summary>
        public Permission()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Permission class.
        /// </summary>
        /// <param name="permissionProperty">Possible values include: 'a', 'r',
        /// 'w'</param>
        /// <param name="type">Possible values include: 'user', 'group'</param>
        public Permission(string partyId, string permissionProperty, string type)
        {
            PartyId = partyId;
            PermissionProperty = permissionProperty;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "partyId")]
        public string PartyId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'a', 'r', 'w'
        /// </summary>
        [JsonProperty(PropertyName = "permission")]
        public string PermissionProperty { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'user', 'group'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PartyId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PartyId");
            }
            if (PermissionProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PermissionProperty");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (PartyId != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(PartyId, "^[0-9a-fA-F]{24}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "PartyId", "^[0-9a-fA-F]{24}$");
                }
            }
        }
    }
}
