// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReportObjectPreferencesPdfRenderingInfo
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ReportObjectPreferencesPdfRenderingInfo class.
        /// </summary>
        public ReportObjectPreferencesPdfRenderingInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ReportObjectPreferencesPdfRenderingInfo class.
        /// </summary>
        /// <param name="paperFormat">Possible values include: 'A0', 'A1',
        /// 'A2', 'A3', 'A4', 'A5', 'legal', 'letter', 'tabloid', 'LEGAL',
        /// 'LETTER', 'TABLOID'</param>
        /// <param name="paperOrientation">Possible values include: 'portrait',
        /// 'landscape'</param>
        /// <param name="layout">Possible values include: 'asis',
        /// 'feed'</param>
        public ReportObjectPreferencesPdfRenderingInfo(string paperFormat = default(string), string paperOrientation = default(string), string layout = default(string), bool? showNarration = default(bool?))
        {
            PaperFormat = paperFormat;
            PaperOrientation = paperOrientation;
            Layout = layout;
            ShowNarration = showNarration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'A0', 'A1', 'A2', 'A3', 'A4',
        /// 'A5', 'legal', 'letter', 'tabloid', 'LEGAL', 'LETTER', 'TABLOID'
        /// </summary>
        [JsonProperty(PropertyName = "paperFormat")]
        public string PaperFormat { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'portrait', 'landscape'
        /// </summary>
        [JsonProperty(PropertyName = "paperOrientation")]
        public string PaperOrientation { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'asis', 'feed'
        /// </summary>
        [JsonProperty(PropertyName = "layout")]
        public string Layout { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "showNarration")]
        public bool? ShowNarration { get; set; }

    }
}
