// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Mail sent info
    /// </summary>
    public partial class ReportingResultMail
    {
        /// <summary>
        /// Initializes a new instance of the ReportingResultMail class.
        /// </summary>
        public ReportingResultMail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReportingResultMail class.
        /// </summary>
        /// <param name="success">Amount success reports sent</param>
        /// <param name="error">Amount error reports sent</param>
        /// <param name="notSent">Amount not sent reports</param>
        /// <param name="groupsBcc">Amount email to sent with BCC for success
        /// reports</param>
        public ReportingResultMail(double? success = default(double?), double? error = default(double?), double? notSent = default(double?), double? groupsBcc = default(double?))
        {
            Success = success;
            Error = error;
            NotSent = notSent;
            GroupsBcc = groupsBcc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets amount success reports sent
        /// </summary>
        [JsonProperty(PropertyName = "success")]
        public double? Success { get; set; }

        /// <summary>
        /// Gets or sets amount error reports sent
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public double? Error { get; set; }

        /// <summary>
        /// Gets or sets amount not sent reports
        /// </summary>
        [JsonProperty(PropertyName = "notSent")]
        public double? NotSent { get; set; }

        /// <summary>
        /// Gets or sets amount email to sent with BCC for success reports
        /// </summary>
        [JsonProperty(PropertyName = "groupsBcc")]
        public double? GroupsBcc { get; set; }

    }
}
