// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReportObjectPreferencesPdf
    {
        /// <summary>
        /// Initializes a new instance of the ReportObjectPreferencesPdf class.
        /// </summary>
        public ReportObjectPreferencesPdf()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReportObjectPreferencesPdf class.
        /// </summary>
        public ReportObjectPreferencesPdf(bool? includeTitle = default(bool?), bool? includeFilters = default(bool?), bool? includeDS = default(bool?), ReportObjectPreferencesPdfRenderingInfo renderingInfo = default(ReportObjectPreferencesPdfRenderingInfo))
        {
            IncludeTitle = includeTitle;
            IncludeFilters = includeFilters;
            IncludeDS = includeDS;
            RenderingInfo = renderingInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeTitle")]
        public bool? IncludeTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeFilters")]
        public bool? IncludeFilters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "includeDS")]
        public bool? IncludeDS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "renderingInfo")]
        public ReportObjectPreferencesPdfRenderingInfo RenderingInfo { get; set; }

    }
}
