// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetSystemSettingsOKResponseReporting
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SetSystemSettingsOKResponseReporting class.
        /// </summary>
        public SetSystemSettingsOKResponseReporting()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SetSystemSettingsOKResponseReporting class.
        /// </summary>
        public SetSystemSettingsOKResponseReporting(SetSystemSettingsOKResponseReportingEndUserScheduling endUserScheduling = default(SetSystemSettingsOKResponseReportingEndUserScheduling))
        {
            EndUserScheduling = endUserScheduling;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endUserScheduling")]
        public SetSystemSettingsOKResponseReportingEndUserScheduling EndUserScheduling { get; set; }

    }
}
