// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TranslationSettings
    {
        /// <summary>
        /// Initializes a new instance of the TranslationSettings class.
        /// </summary>
        public TranslationSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TranslationSettings class.
        /// </summary>
        /// <param name="translationStrategy">Translation strategy</param>
        /// <param name="newTranslatorSupportedProviders">Translator supported
        /// providers</param>
        public TranslationSettings(string translationStrategy = default(string), string newTranslatorSupportedProviders = default(string))
        {
            TranslationStrategy = translationStrategy;
            NewTranslatorSupportedProviders = newTranslatorSupportedProviders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets translation strategy
        /// </summary>
        [JsonProperty(PropertyName = "translationStrategy")]
        public string TranslationStrategy { get; set; }

        /// <summary>
        /// Gets or sets translator supported providers
        /// </summary>
        [JsonProperty(PropertyName = "newTranslatorSupportedProviders")]
        public string NewTranslatorSupportedProviders { get; set; }

    }
}
