// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the UpdateOKResponse class.
        /// </summary>
        public UpdateOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateOKResponse class.
        /// </summary>
        /// <param name="language">Default language for localization.</param>
        public UpdateOKResponse(string language = default(string), UpdateOKResponseLocalization localization = default(UpdateOKResponseLocalization))
        {
            Language = language;
            Localization = localization;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets default language for localization.
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "localization")]
        public UpdateOKResponseLocalization Localization { get; set; }

    }
}
