// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// datasource can be object or string, use "oneOf" when on OpenAPI 3.0 or
    /// higher
    /// </summary>
    public partial class UserLikesObjectItem
    {
        /// <summary>
        /// Initializes a new instance of the UserLikesObjectItem class.
        /// </summary>
        public UserLikesObjectItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserLikesObjectItem class.
        /// </summary>
        public UserLikesObjectItem(object datasource = default(object), UserLikesObjectItemJaql jaql = default(UserLikesObjectItemJaql), bool? liked = default(bool?), string userId = default(string))
        {
            Datasource = datasource;
            Jaql = jaql;
            Liked = liked;
            UserId = userId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "datasource")]
        public object Datasource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jaql")]
        public UserLikesObjectItemJaql Jaql { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "liked")]
        public bool? Liked { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

    }
}
