// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class User
    {
        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User(string _id = default(string), string email = default(string), string userName = default(string), string firstName = default(string), string lastName = default(string), string roleId = default(string), bool? active = default(bool?), IList<string> groups = default(IList<string>), IList<string> adgroups = default(IList<string>), bool? activeDirectory = default(bool?), string principalName = default(string), string objectSid = default(string), string uSNChanged = default(string), string dn = default(string), UserPreferences preferences = default(UserPreferences), object uiSettings = default(object), System.DateTime? created = default(System.DateTime?), string lastLogin = default(string), System.DateTime? lastUpdated = default(System.DateTime?), string ldapDomainId = default(string), System.DateTime? pendingExpiration = default(System.DateTime?), string createdSso = default(string))
        {
            this._id = _id;
            Email = email;
            UserName = userName;
            FirstName = firstName;
            LastName = lastName;
            RoleId = roleId;
            Active = active;
            Groups = groups;
            Adgroups = adgroups;
            ActiveDirectory = activeDirectory;
            PrincipalName = principalName;
            ObjectSid = objectSid;
            USNChanged = uSNChanged;
            Dn = dn;
            Preferences = preferences;
            UiSettings = uiSettings;
            Created = created;
            LastLogin = lastLogin;
            LastUpdated = lastUpdated;
            LdapDomainId = ldapDomainId;
            PendingExpiration = pendingExpiration;
            CreatedSso = createdSso;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public string RoleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groups")]
        public IList<string> Groups { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adgroups")]
        public IList<string> Adgroups { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activeDirectory")]
        public bool? ActiveDirectory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "principalName")]
        public string PrincipalName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "objectSid")]
        public string ObjectSid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uSNChanged")]
        public string USNChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dn")]
        public string Dn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "preferences")]
        public UserPreferences Preferences { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uiSettings")]
        public object UiSettings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastLogin")]
        public string LastLogin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdated")]
        public System.DateTime? LastUpdated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ldapDomainId")]
        public string LdapDomainId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pendingExpiration")]
        public System.DateTime? PendingExpiration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdSso")]
        public string CreatedSso { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (_id != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(_id, "^[0-9a-fA-F]{24}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "_id", "^[0-9a-fA-F]{24}$");
                }
            }
            if (Email != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Email, "^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})|([a-zA-Z\\-0-9]))$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Email", "^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})|([a-zA-Z\\-0-9]))$");
                }
            }
        }
    }
}
