// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V1.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WidgetMetadata
    {
        /// <summary>
        /// Initializes a new instance of the WidgetMetadata class.
        /// </summary>
        public WidgetMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WidgetMetadata class.
        /// </summary>
        public WidgetMetadata(IList<WidgetMetadataPanelsItem> panels = default(IList<WidgetMetadataPanelsItem>))
        {
            Panels = panels;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "panels")]
        public IList<WidgetMetadataPanelsItem> Panels { get; set; }

    }
}
