// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Acl
    {
        /// <summary>
        /// Initializes a new instance of the Acl class.
        /// </summary>
        public Acl()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Acl class.
        /// </summary>
        public Acl(string party = default(string), string permission = default(string), string type = default(string))
        {
            Party = party;
            Permission = permission;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "party")]
        public string Party { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permission")]
        public string Permission { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
