// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AttachParamsDTO
    /// </summary>
    public partial class AttachParamsDTO
    {
        /// <summary>
        /// Initializes a new instance of the AttachParamsDTO class.
        /// </summary>
        public AttachParamsDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AttachParamsDTO class.
        /// </summary>
        public AttachParamsDTO(bool? sync = default(bool?), string uri = default(string))
        {
            Sync = sync;
            Uri = uri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sync")]
        public bool? Sync { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

    }
}
