// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CustomColumnPayload
    {
        /// <summary>
        /// Initializes a new instance of the CustomColumnPayload class.
        /// </summary>
        public CustomColumnPayload()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomColumnPayload class.
        /// </summary>
        public CustomColumnPayload(string columnName = default(string), string tableName = default(string), string customColumnExpression = default(string), MonetDbSchema monetDbSchema = default(MonetDbSchema))
        {
            ColumnName = columnName;
            TableName = tableName;
            CustomColumnExpression = customColumnExpression;
            MonetDbSchema = monetDbSchema;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnName")]
        public string ColumnName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tableName")]
        public string TableName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customColumnExpression")]
        public string CustomColumnExpression { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "monetDbSchema")]
        public MonetDbSchema MonetDbSchema { get; set; }

    }
}
