// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CustomTablePayload
    {
        /// <summary>
        /// Initializes a new instance of the CustomTablePayload class.
        /// </summary>
        public CustomTablePayload()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomTablePayload class.
        /// </summary>
        public CustomTablePayload(string tableName = default(string), string customTableQuery = default(string), MonetDbSchema monetDbSchema = default(MonetDbSchema))
        {
            TableName = tableName;
            CustomTableQuery = customTableQuery;
            MonetDbSchema = monetDbSchema;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tableName")]
        public string TableName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customTableQuery")]
        public string CustomTableQuery { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "monetDbSchema")]
        public MonetDbSchema MonetDbSchema { get; set; }

    }
}
