// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// DataSourcesDTO
    /// </summary>
    public partial class DataSourcesDTO
    {
        /// <summary>
        /// Initializes a new instance of the DataSourcesDTO class.
        /// </summary>
        public DataSourcesDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataSourcesDTO class.
        /// </summary>
        public DataSourcesDTO(string address = default(string), string database = default(string), string fullname = default(string), string id = default(string), bool? live = default(bool?), string title = default(string))
        {
            Address = address;
            Database = database;
            Fullname = fullname;
            Id = id;
            Live = live;
            Title = title;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "database")]
        public string Database { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fullname")]
        public string Fullname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "live")]
        public bool? Live { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

    }
}
