// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeleteManifestByPathOKResponseManifestWidgetsFilters
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeleteManifestByPathOKResponseManifestWidgetsFilters class.
        /// </summary>
        public DeleteManifestByPathOKResponseManifestWidgetsFilters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeleteManifestByPathOKResponseManifestWidgetsFilters class.
        /// </summary>
        public DeleteManifestByPathOKResponseManifestWidgetsFilters(bool? modifyType = default(bool?), bool? onOff = default(bool?), bool? toggleExpansion = default(bool?))
        {
            ModifyType = modifyType;
            OnOff = onOff;
            ToggleExpansion = toggleExpansion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modify_type")]
        public bool? ModifyType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "on_off")]
        public bool? OnOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toggle_expansion")]
        public bool? ToggleExpansion { get; set; }

    }
}
