// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MonetDbSchema
    {
        /// <summary>
        /// Initializes a new instance of the MonetDbSchema class.
        /// </summary>
        public MonetDbSchema()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MonetDbSchema class.
        /// </summary>
        public MonetDbSchema(string schemaId = default(string), string schemaName = default(string), string schemaPhysicalName = default(string), IList<MonetDataTable> tables = default(IList<MonetDataTable>), IList<MonetRelationship> relationships = default(IList<MonetRelationship>), IList<MonetDimensionTable> dimensionTables = default(IList<MonetDimensionTable>))
        {
            SchemaId = schemaId;
            SchemaName = schemaName;
            SchemaPhysicalName = schemaPhysicalName;
            Tables = tables;
            Relationships = relationships;
            DimensionTables = dimensionTables;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaId")]
        public string SchemaId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaName")]
        public string SchemaName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaPhysicalName")]
        public string SchemaPhysicalName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tables")]
        public IList<MonetDataTable> Tables { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationships")]
        public IList<MonetRelationship> Relationships { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dimensionTables")]
        public IList<MonetDimensionTable> DimensionTables { get; set; }

    }
}
