// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MonetDimensionTable
    {
        /// <summary>
        /// Initializes a new instance of the MonetDimensionTable class.
        /// </summary>
        public MonetDimensionTable()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MonetDimensionTable class.
        /// </summary>
        public MonetDimensionTable(string tablePhysicalName = default(string), string monetColumnType = default(string))
        {
            TablePhysicalName = tablePhysicalName;
            MonetColumnType = monetColumnType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tablePhysicalName")]
        public string TablePhysicalName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "monetColumnType")]
        public string MonetColumnType { get; set; }

    }
}
