// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProxySettings
    {
        /// <summary>
        /// Initializes a new instance of the ProxySettings class.
        /// </summary>
        public ProxySettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProxySettings class.
        /// </summary>
        public ProxySettings(bool? enabled = default(bool?), string ip = default(string), double? port = default(double?), string username = default(string), string password = default(string))
        {
            Enabled = enabled;
            Ip = ip;
            Port = port;
            Username = username;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ip")]
        public string Ip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "port")]
        public double? Port { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
