// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResetBrandingNotFoundResponse
    {
        /// <summary>
        /// Initializes a new instance of the ResetBrandingNotFoundResponse
        /// class.
        /// </summary>
        public ResetBrandingNotFoundResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResetBrandingNotFoundResponse
        /// class.
        /// </summary>
        public ResetBrandingNotFoundResponse(ResetBrandingNotFoundResponseError error = default(ResetBrandingNotFoundResponseError))
        {
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public ResetBrandingNotFoundResponseError Error { get; set; }

    }
}
