// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetBrandingOKResponseHomePageConfig
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SetBrandingOKResponseHomePageConfig class.
        /// </summary>
        public SetBrandingOKResponseHomePageConfig()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SetBrandingOKResponseHomePageConfig class.
        /// </summary>
        public SetBrandingOKResponseHomePageConfig(string documentationLink = default(string), bool? hideSearchInNavver = default(bool?), string marketingPart = default(string), bool? hideMarketingBanner = default(bool?), string tutorialsLink = default(string))
        {
            DocumentationLink = documentationLink;
            HideSearchInNavver = hideSearchInNavver;
            MarketingPart = marketingPart;
            HideMarketingBanner = hideMarketingBanner;
            TutorialsLink = tutorialsLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentationLink")]
        public string DocumentationLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hideSearchInNavver")]
        public bool? HideSearchInNavver { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marketingPart")]
        public string MarketingPart { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hideMarketingBanner")]
        public bool? HideMarketingBanner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tutorialsLink")]
        public string TutorialsLink { get; set; }

    }
}
