// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AsyncExportResponse
    /// </summary>
    public partial class AsyncExportResponse
    {
        /// <summary>
        /// Initializes a new instance of the AsyncExportResponse class.
        /// </summary>
        public AsyncExportResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AsyncExportResponse class.
        /// </summary>
        /// <param name="status">Possible values include: 'IDLE', 'RUNNING',
        /// 'CANCELLED', 'FAILED', 'FINISHED', 'UNKNOWN'</param>
        public AsyncExportResponse(string dataSourceId = default(string), string id = default(string), LocalExportConfig local = default(LocalExportConfig), string status = default(string))
        {
            DataSourceId = dataSourceId;
            Id = id;
            Local = local;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataSourceId")]
        public string DataSourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "local")]
        public LocalExportConfig Local { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'IDLE', 'RUNNING',
        /// 'CANCELLED', 'FAILED', 'FINISHED', 'UNKNOWN'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
