// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AsyncImportRequest
    /// </summary>
    public partial class AsyncImportRequest
    {
        /// <summary>
        /// Initializes a new instance of the AsyncImportRequest class.
        /// </summary>
        public AsyncImportRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AsyncImportRequest class.
        /// </summary>
        /// <param name="local">If this property is present, import will be
        /// from local file</param>
        /// <param name="oid">Unique ID assigned to the Import task</param>
        /// <param name="datamodelId">Unique ID of Datamodel to import into.
        /// If provided, Datamodel title is ignored.
        /// If not provided, a new Datamodel will be created</param>
        /// <param name="newTitle">When a `datamodelId` is not provided to
        /// create a new Datamodel, this property can be used to give the new
        /// Datamodel a specific title.
        ///
        /// If `datamodelId` is provided together with `newTitle` an error will
        /// occur.</param>
        /// <param name="type">What should be imported. Possible values
        /// include: 'schema', 'full'</param>
        /// <param name="status">Status of import process. Possible values
        /// include: 'importing', 'done', 'failed'</param>
        public AsyncImportRequest(string dataSourceId = default(string), string dataSourceTitle = default(string), string fileName = default(string), LocalImportConfig local = default(LocalImportConfig), S3ImportConfig s3ImportConfig = default(S3ImportConfig), StreamImportConfig streamImportConfig = default(StreamImportConfig), System.Guid? oid = default(System.Guid?), System.Guid? datamodelId = default(System.Guid?), string newTitle = default(string), string type = default(string), string status = default(string))
        {
            DataSourceId = dataSourceId;
            DataSourceTitle = dataSourceTitle;
            FileName = fileName;
            Local = local;
            S3ImportConfig = s3ImportConfig;
            StreamImportConfig = streamImportConfig;
            Oid = oid;
            DatamodelId = datamodelId;
            NewTitle = newTitle;
            Type = type;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataSourceId")]
        public string DataSourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataSourceTitle")]
        public string DataSourceTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets if this property is present, import will be from local
        /// file
        /// </summary>
        [JsonProperty(PropertyName = "local")]
        public LocalImportConfig Local { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "s3ImportConfig")]
        public S3ImportConfig S3ImportConfig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streamImportConfig")]
        public StreamImportConfig StreamImportConfig { get; set; }

        /// <summary>
        /// Gets or sets unique ID assigned to the Import task
        /// </summary>
        [JsonProperty(PropertyName = "oid")]
        public System.Guid? Oid { get; set; }

        /// <summary>
        /// Gets or sets unique ID of Datamodel to import into.
        /// If provided, Datamodel title is ignored.
        /// If not provided, a new Datamodel will be created
        /// </summary>
        [JsonProperty(PropertyName = "datamodelId")]
        public System.Guid? DatamodelId { get; set; }

        /// <summary>
        /// Gets or sets when a `datamodelId` is not provided to create a new
        /// Datamodel, this property can be used to give the new Datamodel a
        /// specific title.
        ///
        /// If `datamodelId` is provided together with `newTitle` an error will
        /// occur.
        /// </summary>
        [JsonProperty(PropertyName = "newTitle")]
        public string NewTitle { get; set; }

        /// <summary>
        /// Gets or sets what should be imported. Possible values include:
        /// 'schema', 'full'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets status of import process. Possible values include:
        /// 'importing', 'done', 'failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Oid != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Oid.ToString(), "^[0-9a-f]{8}(-?[0-9a-f]{4}){3}-?[0-9a-f]{4,12}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Oid", "^[0-9a-f]{8}(-?[0-9a-f]{4}){3}-?[0-9a-f]{4,12}$");
                }
            }
            if (DatamodelId != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(DatamodelId.ToString(), "^[0-9a-f]{8}(-?[0-9a-f]{4}){3}-?[0-9a-f]{4,12}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "DatamodelId", "^[0-9a-f]{8}(-?[0-9a-f]{4}){3}-?[0-9a-f]{4,12}$");
                }
            }
        }
    }
}
