// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// BuildInfoListDTO
    /// </summary>
    public partial class BuildInfoListDTO
    {
        /// <summary>
        /// Initializes a new instance of the BuildInfoListDTO class.
        /// </summary>
        public BuildInfoListDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BuildInfoListDTO class.
        /// </summary>
        public BuildInfoListDTO(IList<BuildInfoDTO> builds = default(IList<BuildInfoDTO>))
        {
            Builds = builds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "builds")]
        public IList<BuildInfoDTO> Builds { get; set; }

    }
}
