// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// DataGroupServiceResponseListDataGroupDto
    /// </summary>
    public partial class DataGroupServiceResponseListDataGroupDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DataGroupServiceResponseListDataGroupDto class.
        /// </summary>
        public DataGroupServiceResponseListDataGroupDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DataGroupServiceResponseListDataGroupDto class.
        /// </summary>
        /// <param name="status">Possible values include: 'OK',
        /// 'DATA_GROUP_NOT_FOUND', 'DATA_GROUP_NAME_EXISTS',
        /// 'INVALID_DATA_MODEL_NAME', 'CANNOT_DELETE_DEFAULT',
        /// 'CANNOT_DELETE_CUBES_ATTACHED', 'INVALID_NODE_TYPE',
        /// 'UNAUTHORIZED', 'INTERNAL'</param>
        public DataGroupServiceResponseListDataGroupDto(string error = default(string), string status = default(string), int? statusCode = default(int?), IList<DataGroupDto> value = default(IList<DataGroupDto>))
        {
            Error = error;
            Status = status;
            StatusCode = statusCode;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'OK', 'DATA_GROUP_NOT_FOUND',
        /// 'DATA_GROUP_NAME_EXISTS', 'INVALID_DATA_MODEL_NAME',
        /// 'CANNOT_DELETE_DEFAULT', 'CANNOT_DELETE_CUBES_ATTACHED',
        /// 'INVALID_NODE_TYPE', 'UNAUTHORIZED', 'INTERNAL'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DataGroupDto> Value { get; set; }

    }
}
