// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DatamodelSchemaInput
    {
        /// <summary>
        /// Initializes a new instance of the DatamodelSchemaInput class.
        /// </summary>
        public DatamodelSchemaInput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DatamodelSchemaInput class.
        /// </summary>
        /// <param name="title">Datamodel title (name)</param>
        /// <param name="server">*Legacy*: Hostname of server on which the
        /// Datamodel is created.
        /// **Only applies to Windows versions.**
        /// Defaults to `LocalHost`.</param>
        /// <param name="type">Datamodel type; `extract` type Datamodels are
        /// formerly known as Elasticube. Possible values include: 'live',
        /// 'extract'</param>
        public DatamodelSchemaInput(string title, string server = default(string), string type = default(string))
        {
            Title = title;
            Server = server;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets datamodel title (name)
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets *Legacy*: Hostname of server on which the Datamodel is
        /// created.
        /// **Only applies to Windows versions.**
        /// Defaults to `LocalHost`.
        /// </summary>
        [JsonProperty(PropertyName = "server")]
        public string Server { get; set; }

        /// <summary>
        /// Gets or sets datamodel type; `extract` type Datamodels are formerly
        /// known as Elasticube. Possible values include: 'live', 'extract'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Title == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Title");
            }
        }
    }
}
