// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// DataGroupQualityOfService
    /// </summary>
    public partial class DataGroupQualityOfService
    {
        /// <summary>
        /// Initializes a new instance of the DataGroupQualityOfService class.
        /// </summary>
        public DataGroupQualityOfService()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataGroupQualityOfService class.
        /// </summary>
        public DataGroupQualityOfService(int? concurrentQueries = default(int?), int? queryTimeout = default(int?), int? replicaScaleMax = default(int?), int? replicaScaleMin = default(int?))
        {
            ConcurrentQueries = concurrentQueries;
            QueryTimeout = queryTimeout;
            ReplicaScaleMax = replicaScaleMax;
            ReplicaScaleMin = replicaScaleMin;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "concurrentQueries")]
        public int? ConcurrentQueries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "queryTimeout")]
        public int? QueryTimeout { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "replicaScaleMax")]
        public int? ReplicaScaleMax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "replicaScaleMin")]
        public int? ReplicaScaleMin { get; set; }

    }
}
