// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// DeploymentServiceResponseVoid
    /// </summary>
    public partial class DeploymentServiceResponseVoid
    {
        /// <summary>
        /// Initializes a new instance of the DeploymentServiceResponseVoid
        /// class.
        /// </summary>
        public DeploymentServiceResponseVoid()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeploymentServiceResponseVoid
        /// class.
        /// </summary>
        /// <param name="status">Possible values include: 'OK',
        /// 'INTERNAL_ERROR', 'NODE_NOT_FOUND', 'NODE_ALREADY_EXISTS',
        /// 'UNAUTHORIZED'</param>
        public DeploymentServiceResponseVoid(string error = default(string), string status = default(string), int? statusCode = default(int?))
        {
            Error = error;
            Status = status;
            StatusCode = statusCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'OK', 'INTERNAL_ERROR',
        /// 'NODE_NOT_FOUND', 'NODE_ALREADY_EXISTS', 'UNAUTHORIZED'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

    }
}
