// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// EcmModel
    /// </summary>
    public partial class EcmModel
    {
        /// <summary>
        /// Initializes a new instance of the EcmModel class.
        /// </summary>
        public EcmModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EcmModel class.
        /// </summary>
        public EcmModel(string buildDestination = default(string), IList<Dataset> datasets = default(IList<Dataset>), string lastBuildAttempt = default(string), string lastBuildTime = default(string), string lastUpdated = default(string), IList<object> modelingTransformations = default(IList<object>), string oid = default(string), IList<Relation> relations = default(IList<Relation>), string schemaId = default(string), string server = default(string), string title = default(string))
        {
            BuildDestination = buildDestination;
            Datasets = datasets;
            LastBuildAttempt = lastBuildAttempt;
            LastBuildTime = lastBuildTime;
            LastUpdated = lastUpdated;
            ModelingTransformations = modelingTransformations;
            Oid = oid;
            Relations = relations;
            SchemaId = schemaId;
            Server = server;
            Title = title;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildDestination")]
        public string BuildDestination { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "datasets")]
        public IList<Dataset> Datasets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastBuildAttempt")]
        public string LastBuildAttempt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastBuildTime")]
        public string LastBuildTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastUpdated")]
        public string LastUpdated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modeling-transformations")]
        public IList<object> ModelingTransformations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "oid")]
        public string Oid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relations")]
        public IList<Relation> Relations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaId")]
        public string SchemaId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "server")]
        public string Server { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

    }
}
