// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// S3ImportConfig
    /// </summary>
    public partial class S3ImportConfig
    {
        /// <summary>
        /// Initializes a new instance of the S3ImportConfig class.
        /// </summary>
        public S3ImportConfig()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the S3ImportConfig class.
        /// </summary>
        public S3ImportConfig(string accessKey = default(string), string bucketName = default(string), string objectName = default(string), string region = default(string), string secretKey = default(string))
        {
            AccessKey = accessKey;
            BucketName = bucketName;
            ObjectName = objectName;
            Region = region;
            SecretKey = secretKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessKey")]
        public string AccessKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bucketName")]
        public string BucketName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "objectName")]
        public string ObjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "region")]
        public string Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secretKey")]
        public string SecretKey { get; set; }

    }
}
