// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SqlMetaData
    /// </summary>
    public partial class SqlMetaData
    {
        /// <summary>
        /// Initializes a new instance of the SqlMetaData class.
        /// </summary>
        public SqlMetaData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SqlMetaData class.
        /// </summary>
        public SqlMetaData(IList<string> headers = default(IList<string>), IList<ColumnMetaData> metadata = default(IList<ColumnMetaData>))
        {
            Headers = headers;
            Metadata = metadata;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "headers")]
        public IList<string> Headers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public IList<ColumnMetaData> Metadata { get; set; }

    }
}
