// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UnOffSiSenseDotNet.V2_0.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TooManyRequestsApiError
    {
        /// <summary>
        /// Initializes a new instance of the TooManyRequestsApiError class.
        /// </summary>
        public TooManyRequestsApiError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TooManyRequestsApiError class.
        /// </summary>
        public TooManyRequestsApiError(TooManyRequestsApiErrorError error = default(TooManyRequestsApiErrorError))
        {
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public TooManyRequestsApiErrorError Error { get; set; }

    }
}
